#!/bin/bash

ret=$(curl --silent ipecho.net/plain)

interfaces=($(ifconfig -a | sed -ne 's/^\([0-9a-z]\+\).*/\1/p' | grep -vx -e 'lo[0-9]*'))
for interface in "${interfaces[@]}"; do
    ret="${ret}$(ifconfig $interface | grep 'inet ' | awk "{print \" $interface \" \$2}")"
done

[[ ! -z $ret ]] && echo "$ret  "
